# Generated by Django 5.0.6 on 2026-01-06 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='نوع المركبة')),
                ('availability_status', models.CharField(choices=[('available', 'متاح'), ('busy', 'مشغول'), ('offline', 'غير متصل')], default='available', max_length=20, verbose_name='حالة التوفر')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم العنصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='رابط الصورة')),
                ('availability_status', models.CharField(choices=[('available', 'متاح'), ('unavailable', 'غير متاح'), ('out_of_stock', 'نفذت الكمية')], default='available', max_length=20, verbose_name='حالة التوفر')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('preparing', 'قيد التحضير'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المطعم')),
                ('address', models.TextField(verbose_name='عنوان المطعم')),
                ('phone', models.CharField(max_length=15, verbose_name='هاتف المطعم')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم')),
                ('cuisine_type', models.CharField(max_length=100, verbose_name='نوع المطبخ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(choices=[('assigned', 'تم التعيين'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='assigned', max_length=20, verbose_name='حالة التوصيل')),
                ('estimated_time', models.DateTimeField(verbose_name='الوقت المقدر للتوصيل')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='الوقت الفعلي للتوصيل')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='food_delivery.driver', verbose_name='السائق')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='food_delivery.order', verbose_name='الطلب')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='food_delivery.menu', verbose_name='عنصر القائمة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_delivery.order', verbose_name='الطلب')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('card', 'بطاقة ائتمانية'), ('paypal', 'PayPal'), ('cash', 'نقدي عند الاستلام')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('refunded', 'تم الاسترداد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='food_delivery.order', verbose_name='الطلب')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food_delivery.restaurant', verbose_name='المطعم'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='food_delivery.restaurant', verbose_name='المطعم'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='تعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food_delivery.order', verbose_name='الطلب')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food_delivery.restaurant', verbose_name='المطعم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food_delivery.user', verbose_name='المستخدم')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food_delivery.user', verbose_name='المستخدم'),
        ),
    ]
