# Generated by Django 5.0.6 on 2026-01-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
